version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: jdbc:postgresql://postgres:5432/dataservices
      MONGODB_URI: mongodb://mongodb:27017/dataservices
      REDIS_HOST: redis

volumes:
  postgres_data:
  mongodb_data: