global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scalable-data-services'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s